org.gradle.jvmargs=-Xmx1G

mod_group_id=liltojustice
mod_id=trueadaptivemusicapi
mod_version=1.3.7
mod_name=True Adaptive Music API
mod_description=API Functionality for True Adaptive Music
mod_authors=LilTOJustice
mod_home=https://github.com/LilTOJustice/TrueAdaptiveMusicAPI
mod_issues=https://github.com/LilTOJustice/TrueAdaptiveMusicAPI/issues
mod_source=https://github.com/LilTOJustice/TrueAdaptiveMusicAPI
mod_license=GPL-3.0
mod_icon=assets/trueadaptivemusicapi/icon.png
archives_base_name=TrueAdaptiveMusicAPI

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=1.21.1

# Fabric
fabric_loader_version=0.19.3
fabric_kotlin_version=1.13.10+kotlin.2.3.20
fabric_version=0.116.13+1.21.1

# NeoForge
forge_kotlin_version=5.12.0
neoforge_version=21.1.235
neoforge_version_range=[1,)
neoforge_loader_version_range=[5.3,)

# Common
java_version=21