<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>liltojustice</groupId>
    <artifactId>trueadaptivemusicapi</artifactId>
    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/liltojustice/TrueAdaptiveMusicAPI</url>
        </repository>
    </distributionManagement>

    <modules>
        <module>fabric/pom.xml</module>
        <module>neoforge/pom.xml</module>
    </modules>
</project>